spring:
  application:
    name: rag-hybrid-spring-kotlin

llm:
  http:
    connect-timeout: 3s
  ollama:
    base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    request-timeout: 30s
    model: ${DEFAULT_CHAT_MODEL:llama3.2:3b}
    keep-alive: 0s
    provider-tag: ${OLLAMA_PROVIDER_TAG:ollama}

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "metrics" ]
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /docs

guardrails:
  rate-limit:
    enabled: true
    emit-headers: true
    default-rule:
      capacity: 10
      refill: 10
      period: 10s
    overrides:
      "/v1/chat":
        capacity: 3
        refill: 3
        period: 30s
      "/v1/chat/stream":
        capacity: 3
        refill: 3
        period: 30s