spring:
  application:
    name: rag-hybrid-spring-kotlin
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

llm:
  http:
    connect-timeout: 3s
  ollama:
    base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    request-timeout: 30s
    model: ${DEFAULT_CHAT_MODEL:qwen2.5:7b-instruct}
    keep-alive: 0s
    provider-tag: ${OLLAMA_PROVIDER_TAG:ollama}

retrieval:
  embedding:
    provider: ollama
    model: ${OLLAMA_EMBED_MODEL:mxbai-embed-large}
    dimension: 1024
    normalized: true
  search:
    k: 10
    vector:
      enabled: true
      width: 100
    bm25:
      enabled: true
      width: 100
      term-frequency-saturation: 1.2
      length-normalization: 0.75
      stop-words-enabled: true
      stop-words:
        # EN
        - "the"
        - "and"
        - "of"
        - "to"
        - "in"
        - "on"
        - "a"
        - "an"
        - "is"
        - "are"
        # PT-BR
        - "de"
        - "da"
        - "do"
        - "das"
        - "dos"
        - "e"
        - "para"
        - "por"
        - "em"
        - "no"
        - "na"
        - "nos"
        - "nas"
        - "um"
        - "uma"
  fusion:
    alpha: 0.5
  dedup:
    strict-enabled: true
    soft:
      enabled: true
      overlap-threshold: 0.75
  mmr:
    enabled: true
    lambda: 0.3
  ask:
    contextBudgetChars: 3000
    poolK: 12
    maxChunksPerDoc: 2
    language:
      autoDetect: true
    prompt:
      requireCitations: true
      requireAdmitUnknown: true

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "metrics" ]
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, ollama

springdoc:
  swagger-ui:
    path: /docs

guardrails:
  rate-limit:
    enabled: true
    emit-headers: true
    default-rule:
      capacity: 10
      refill: 10
      period: 10s
    overrides:
      "/v1/chat":
        capacity: 3
        refill: 3
        period: 30s
      "/v1/chat/stream":
        capacity: 3
        refill: 3
        period: 30s
      "/v1/retrieval/ingest":
        capacity: 2
        refill: 2
        period: 60s
      "/v1/retrieval/search":
        capacity: 6
        refill: 6
        period: 10s
      "/v1/retrieval/{documentId}":
        capacity: 2
        refill: 2
        period: 60s
      "/v1/retrieval/ask":
        capacity: 6
        refill: 6
        period: 10s