spring:
  application:
    name: rag-hybrid-spring-kotlin

llm:
  http:
    connect-timeout: 3s
  ollama:
    base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
    request-timeout: 30s
    model: ${DEFAULT_CHAT_MODEL:llama3.2:3b}
    keep-alive: 0s

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "metrics" ]
  endpoint:
    health:
      probes:
        enabled: true